# Generated by Django 4.2.4 on 2023-08-31 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(default=1, max_length=48, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='laptop_mockup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Mockup ноутбука'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='location',
            field=models.CharField(default=1, max_length=64, verbose_name='Локация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone_mockup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Mockup телефона'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone_number',
            field=models.CharField(default=1, max_length=18, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='photo_about_me',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_about_me',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_form',
            field=models.TextField(default=1, verbose_name='Подзаголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_form',
            field=models.CharField(default=1, max_length=32, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_portfolio',
            field=models.CharField(default=1, max_length=16, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_services',
            field=models.CharField(default=1, max_length=32, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_skills',
            field=models.CharField(default=1, max_length=16, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
