# Generated by Django 4.2.4 on 2023-08-31 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0004_servicesitem_skillitem_simpletext_offeritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillitem',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Иконка'),
        ),
    ]
