# Generated by Django 4.2.4 on 2023-09-01 11:38

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_skillitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='home.homepage'),
        ),
        migrations.AlterField(
            model_name='servicesitem',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_items', to='home.homepage'),
        ),
        migrations.AlterField(
            model_name='skillitem',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_items', to='home.homepage'),
        ),
    ]
