# Generated by Django 4.2.4 on 2023-09-01 12:16

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_offeritem_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='home.homepage'),
        ),
    ]
