# Generated by Django 4.2.4 on 2023-09-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0011_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_link_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_link_title',
            field=models.CharField(default=1, max_length=32, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_link_url',
            field=models.URLField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
