# Generated by Django 4.2.4 on 2023-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_portfolioitem_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
