# Generated by Django 4.2.4 on 2023-09-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_portfolioitem_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='descriptions',
            new_name='description',
        ),
    ]
