# Generated by Django 4.2.4 on 2023-09-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_applicationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, verbose_name='Прочитано?'),
        ),
    ]
