# Generated by Django 4.2.4 on 2023-09-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_applicationform_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
